### ISSUE TITLE
Tempo Rounding Problem

### ISSUE THREAD

**Issue by Jorbf13** [grimmdude/MidiWriterJS#25]
Tempo is rounded to 4 decimals, f.ex. 163.9998 instead of 164bpm. I can really only visualize this in logic (garageband rounds the number down and ableton rounds it up).

**Comment by Jorbf13** [comment]
@lplume Tempo is still not rounded, and the note placement gets messed up

**Comment by grimmdude** [comment]
Hi @Jorbf13 

I tested the file generated from the below script in Logic X and Garageband and the tempo seems to carry correctly in both.  Seems like it should be simple math; 60000000 / 375000 = 160 exactly.  Could you post, or link to, and example script/midi which is causing the problem for you?

```javascript
var MidiWriter = require('./build/index');
var tracks = [];
tracks[0] = new MidiWriter.Track();
tracks[0]
	.setTempo(160)
	.addEvent([new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4'}),
		new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4'}),
		new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4'}),
		new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4'})]);

var write = new MidiWriter.Writer(tracks);
//console.log(write.dataUri());
write.stdout();
```

**Comment by lplume** [comment]
The way that MidiWriterJS use to set tempo is exactly how MIDI file format want it to be, looking at supports forum of software like cubase, ableton seems lot of people got troubles with "timing" while importing a midi file; also, many repos likes this got this issue pop up soon or later. That said, in this week im gonna try some combination of import/export from and to DAW/MIDI editor via MIDI file, to see what happen.

@grimmdude did you try to change tempo after some note events? It sounds strange that changeing the division messed up all the ticking. Let's rule this timing thing :D !

regards

**Comment by Jorbf13** [comment]
@grimmdude I will share my files/code gladly, but could you try setting the tempo to 164 or 180? I am only getting the rounding issue with certain specific tempos, and not all of them, for instance 160 works fine for me, as well. Those are two examples of bad rounding. Let me know if you still would like to see my code after trying this.
In order to see the 4-decimal number in Logic you will have to check the global Tempo tracking.

Thanks!

**Comment by grimmdude** [comment]
Hi @Jorbf13 ,

I see why this is happening, but I'm not sure what the solution is.  For instance:

`60000000 / 164 = 365853.65853658534`

Currently we round that value at https://github.com/grimmdude/MidiWriterJS/blob/master/src/track.js#L59 but when you multiply it out after rounding this is the result 

`60000000 / 365854 = 163.9998469334762`

MIDI file format only allows three bytes to represent a tempo value, so I'm not sure if a number with decimal places will translate correctly to hex.  I think I added the rounding because that was causing an issue.  If you or @lplume have any ideas on how to fix that I'm all ears.

-Garrett

**Comment by grimmdude** [comment]
I'm going to close this out for now, but feel free to open if you have any solution.

-Garrett
