### ISSUE TITLE
Triplets doesnt Fit the Grid

### ISSUE THREAD

**Issue by nonebits** [grimmdude/MidiWriterJS#69]
Hello!When i try to create a pattern with Triplets and export the generated MIDI file to the DAW (Ableton or Bitwig) they doesnt fit the Grid Subdivisions and begin to be little out of Project Tempo.

Thanks!

**Comment by grimmdude** [comment]
Hi @nonebits,

Thanks for your message, I'll have to take a look at that.  Are you still seeing it?

-Garrett

**Comment by niieani** [comment]
This is still an issue. If you have a 4/4 time signature and fill it up with `8t` notes, it's going to misalign and the beat note will fall slightly before the beginning of the 2nd bar. The further you go, the worse this gets.

**Comment by niieani** [comment]
Ok, so I dug into this a little. The problem won't be easy to fix.

https://github.com/grimmdude/MidiWriterJS/blob/1233a12d24c2b765abdb0e9db465e8dd477e570a/src/utils.js#L181

The rounding here is being done per-note. But this means we don't know how it fits into the bar. Some are rounded down making the notes faster, some are rounded up, making the notes quicker.

I think one way to do this would be to keep the notes not (float), or maybe even as their original note durations, and only round them when serializing to MIDI at the last stage - in the writer. Because some notes need to be rounded down and some rounded up to fit the grid.
