### ISSUE TITLE
Can the NoteEvent.wait option be specified without NoteEvent.duration?

### ISSUE THREAD

**Issue by pelevesque** [grimmdude/MidiWriterJS#76]
I want to make an eight note rest.

When I try to specify a wait time without the duration like so:

```new MidiWriter.NoteEvent({wait: '8'})```

I get the following error which occurs at: node_modules/midi-writer-js/build/index.js:275:27

```TypeError: Cannot read property 'toString' of undefined```

I was obliged to write:

```new MidiWriter.NoteEvent({wait: '8',     duration: '0'})```

This feels really strange and counterintuitive - I'm guessing I misunderstood something in the API.

**Comment by grimmdude** [comment]
Hi @pelevesque,

The `wait` option always needs to be accompanied by a `pitch` and `duration`.  So if you want to write an eigth note rest you would include it with the next note event:

```js
new MidiWriter.NoteEvent({wait: '8', pitch: 'C4', duration: '4'});
```

Reason for this design is because rests will always be followed by some other event, otherwise it would just be the end of the track.

**Comment by pelevesque** [comment]
I see, thank you.
